#!/bin/sh
#
# Plugin to monitor ioDrive iodrive reserves 

#%# family=auto
#%# capabilities=autoconf

if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi

if [ "$1" = "config" ] ; then
        echo "graph_args -r --lower-limit 0 ";
        echo "graph_title ioDrive reserves";
        echo "graph_category iodrive";
        echo "graph_info reserve space";
        echo 'graph_vlabel %'

        echo "cur.label reserves"
        echo "cur.draw AREA"
        echo "cur.type GAUGE"
        exit
fi

/usr/bin/fio-status --all | awk ' /Reserve space status/ { print "cur.value",$6}' | sed -e "s/..$//";
 

